### ISSUE TITLE
Old-style parent class references

### ISSUE THREAD

**Issue by denismakogon** [SergeyPirogov/python-testcontainers#3]
[Old-style reference](https://github.com/SergeyPirogov/testcontainers_python/blob/master/testcontainers/generic.py#L27)

Use new class parent reference using `super(cls, self).method(*args, **kwargs)`

**Comment by denismakogon** [comment]
[Another one](https://github.com/SergeyPirogov/testcontainers_python/blob/master/testcontainers/postgres.py#L18)

**Comment by SergeyPirogov** [comment]
@denismakogon is this new style available in python 2.7?

**Comment by SergeyPirogov** [comment]
fixed https://github.com/SergeyPirogov/python-testcontainers/commit/72423cadd42fe7c7b98ff642501171b674df5f19

**Comment by denismakogon** [comment]
Thanks
